### PR TITLE
Second prototype

### PR DESCRIPTION
**Pull request by Jimvy**
Work in progress to merge the minhprg/master branch in it and test that everything works.

### CODE REVIEW

**Comment by Jimvy** [comment]
Still work in progress...

**Comment by Jimvy** [comment]
Merge finished. Ready

**Comment by Jimvy** [comment]
In case we make additional modifications to the code (like adding tests), can we add them to this PR ? Or we will include them next week.

**Comment by minhprg** [comment]
Thank you

**Pull request merged**
